### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by techtangents** [markhibberd/route#2]
Hi Mark,

I'm keen to update this to newer language/lib versions and do some minor cleanup. I can send a PR soon, if you wish. Just had a few questions first.
1. Is your repo.mth.io repo still alive? 
2. Intellij files in git. My Intellij wants to update lots of things. Would you prefer I update the intellij files or remove them from the repo?
3. You good with piecemeal scalaz imports?

I'd like to bump:
- scala to 2.11.8 
- scalaz to 7.2.5
- specs2 to 3.8.4
- scalacheck to 1.13.2

Cheers,

Dylan

**Comment by markhibberd** [comment]
1. should be, 2/3) Happy with what ever works for you. If you chuck something up, I will give you commit access and work out a way for the builds to be published without having to wait for me - as you may be waiting for a while if you get stuck in my queue.

**Comment by techtangents** [comment]
1. I probably just don't have access to it - it's 403'ing for me.
   2/3. Cheers.

I'll push something up - merge at your leisure. We'll publish to our internal sbt server in the meantime.

**Comment by techtangents** [comment]
Closing old issue. These changes are no longer needed.
